version: '3'
services:
  playwright-test:
    build: .
    container_name: playwright_api_tests
    volumes:
      - .:/app
    environment:
      - CI=true
    entrypoint: ["npx", "playwright", "test"]