name: Playwright Tests
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - name: Kódbázis letöltése
      uses: actions/checkout@v4
    
    - name: Node.js beállitása
      uses: actions/setup-node@v4
      with:
        node-version: lts/*

    - name: Install dependencies
      run: npm install #ci
      
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps

    - name: API tesztek futtatása
      run: npx playwright test tests/apiTest.spec.ts

    - name: Run Playwright tests
      run: npx playwright test --reporter=html
    - uses: actions/upload-artifact@v4
    
      if: always()
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 7
